### ISSUE TITLE
Dispose store !! ???

### ISSUE THREAD

**Issue by bhanu7755** [AhsanAyaz/angular4-rockstar-chat-ngrx#1]
Hi Ayaz,

Your solution looks great. I'm trying to address similar issue in my project but the question I got is how did you handled disposing stores (if needed) ?? 

I want to create store for some forms to maintain state of the application and once the form got closed it should be disposed to avoid memory leaks. I couldn't find proper solution anywhere.

Thanks in advance.

**Comment by AhsanAyaz** [comment]
Hi @bhanu7755 . 
I think the question is not related to this repo but regarding ngrx store and rxjs. 
Still, what I think of right now is that the memory leaks might come from the observables (selectors) as well as from the state (the store). My suggestion would be to unsubscribe any selectors on `ngDestroy` lifecycle and reset the state to initial (with no data) as well on `ngDestroy` (where needed). Hope that helps. Closing the issue.
